name: stock_app
description: 股票分析 App

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.4.0
  cupertino_icons: ^1.0.6

flutter:
  uses-material-design: true